FROM node:18-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}
COPY frontend/index.html    ./
COPY frontend/vite.config.js ./
COPY frontend/src           ./src
COPY frontend/public        ./public
RUN npm run build

FROM nginx:alpine
RUN apk add --no-cache gettext
COPY --from=build /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf.template /etc/nginx/conf.d/default.conf.template
COPY frontend/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
CMD ["/docker-entrypoint.sh"]
